name: TankLib
on:
    push:
        branches: [ develop ]
    pull_request:
        branches: [ develop ]
jobs:
    build:
        runs-on: windows-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
                    submodules: 'recursive'
            -   name: Install .NET 8
                uses: actions/setup-dotnet@v4
            -   name: Mutate Run Number
                run: |
                  $num = (997+$($Env:GITHUB_RUN_NUMBER))
                  echo "GITHUB_RUN_NUMBER_DELTA=$num" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
            -   name: Restore project
                run: dotnet restore OverwatchToolchain.sln --verbosity m -r win-x64 -p:TargetFramework=net8.0
            -   name: Build Release
                run: dotnet publish --configuration ReleasePublish -r win-x64 -o dist/Release --self-contained true
                # --self-contained for https://github.com/dotnet/sdk/issues/29642
            -   name: Upload Release
                uses: actions/upload-artifact@v4
                with:
                    name: toolchain-release
                    path: dist/Release
            -   name: Build Debug
                run: dotnet publish --configuration DebugPublish -r win-x64 -o dist/Debug --self-contained true
            -   name: Upload Debug
                uses: actions/upload-artifact@v4
                with:
                    name: toolchain-debug
                    path: dist/Debug
